[project]
name = "ifly-workflow-mcp-server"
version = "1.0.0"
description = "This a simple implementation of an MCP server using iFlytek. It enables calling iFlytek workflows through MCP tools."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx==0.28.1",
    "mcp==1.5.0",
    "omegaconf==2.3.0",
    "pip==25.0.1",
    "pytest==8.3.5",
    "python-dotenv==1.0.1",
    "requests==2.32.3",
]

[build-system]
requires = ["hatchling", ]
build-backend = "hatchling.build"

[project.scripts]
ifly_workflow_mcp_server = "mcp_server:main"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_server"]
